services:
  server:
    container_name: server
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    depends_on:
       - db
  db:
    image: postgres:latest
    container_name: database
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=vk
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=123
    expose:
      - 5432
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5